### PR TITLE
Template Branch Updates

### PR DESCRIPTION
**Pull request by hollyschinsky**
There will be some major changes coming with this branch and this PR is meant to be a place for continuous discussion and commits on all items related. 

Also, I will update this with the latest developer workflow based on my commit [here](https://github.com/phonegap/phonegap-app-desktop/commit/2baf92ac6f14130ab129a86bc884af949b8f2966).

### CODE REVIEW

**Comment by hollyschinsky** [comment]
There are still some issues that need to be resolved concerning timing and project creation based on my latest testing to figure out issues noticed by @hermwong and @surajpindoria . 

Here are some notes:

**1. @hermwong noticed the default template name and generic icon would sometimes be used rather than the project name chosen and icon that is specifically included for that template. Herm noted this happened intermittently while testing *HelloWorld* template on Windows.**

I've been testing this and found that this issue is not just Windows only but related to us having to do a bit of a hack to check for the`config.xml` rather than wait for the true process exit code. It specifically happens with templates like *Hello World* and *Push* that have `config.xml` in their `www` folders rather than in the root. In my testing with these templates I found there's a point in the project creation process where the projects temporarily have two `config.xml` files, one in the root and one in `www`. 

screen shot 2016-08-12 at 6 48 58 pm

Notice the different sizes because the one in the root at this moment is the default `config.xml` created from the Cordova CLI. The one in the `www` is the one that's supposed to be used. 

This causes an issue due to us using the watcher to look for the `config.xml` creation and then continue to add the project based on that but it will sometimes find the cordova one first and use that.  We see the end result of the project has the correct `config.xml` in the root and not the `www` when based on these projects due to the [PhoneGap CLI code here](https://github.com/phonegap/phonegap-cli/blob/595-desktop-support/lib/phonegap/create.js#L142-L145) that moves the right one to the root.  

**2. @surajpindoria noticed if he creates a project based on a template containing plugins, then immediately tries to serve it, it will usually produce an error. This is because of timing again, because the **browser** platform hasn't been fully added with the plugins it needs. If he waits for the process exit it works correctly.**

We could fix both of these problems by going back to waiting for the exit code 0 from the child process but we still have to deal with the noticeable time lag (~45-50 secs).  From testing some more phonegap CLI commands today, it seems the it does create some extra overhead in general. Perhaps due to the double spawning of process to PG CLI then Cordova CLI. Switching to using Cordova CLI directly saves time - where the exit code is usually received within about ~27 seconds. 

It's possible this could be helped by [the decoupling work @stevengill is doing](https://github.com/phonegap/phonegap-roadmap/issues/34). 

We could also try to qualify our file watcher further to ensure it's only adding the project when the necessary files are available. Not ideal. Or we could use the Cordova CLI directly to help minimize the time some. 

Thoughts/ideas welcome...

**Comment by hollyschinsky** [comment]
I ran some tests with using the PhoneGap and Cordova CLI's with different commands from the Desktop app (spawning a child process) and pasted the results below for futher discussion. The arguments used for each are shown in the first line with the time it took to run shown on the last line for each command:

### Version command

#### PhoneGap CLI (`phonegap -v`)
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/phonegap/bin/phonegap.js","-v"]
project-create-open-handlers.js:171 CREATE *START* AT: Mon, 15 Aug 2016 11:39:37 GMT
project-create-open-handlers.js:183 CLOSE *COMPLETE* AT Mon, 15 Aug 2016 11:40:14 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time 36.865 seconds.
```

#### Cordova CLI (`cordova -v`)
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/cordova/bin/cordova","-v"]
project-create-open-handlers.js:171 CREATE *START* AT: Mon, 15 Aug 2016 11:41:27 GMT
project-create-open-handlers.js:183 CLOSE *COMPLETE* AT Mon, 15 Aug 2016 11:41:28 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time 0.906 seconds.
```
--------------------------------------------------------------------------------------------------

### Create with --copy-from 

#### PhoneGap CLI (`phonegap create --copy-from...`) 
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/phonegap/bin/phonegap.js","create","/Users/hschinsk/phonegap-apps/pgCopy","--copy-from=/Users/hschinsk/.cordova/lib/npm_cache/phonegap-template-blank/1.1.0/package","--id","com.phonegap.helloworld","--name","pgCopy"]
project-create-open-handlers.js:171 CREATE *START* AT: Mon, 15 Aug 2016 11:46:44 GMT
project-create-open-handlers.js:183 CREATE CLOSE *COMPLETE* AT Mon, 15 Aug 2016 11:47:21 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time to create project 36.884 seconds.
```

#### Cordova CLI (`cordova create --copy-from...`) 
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/cordova/bin/cordova","create","/Users/hschinsk/phonegap-apps/cordovaCopy","--copy-from=/Users/hschinsk/.cordova/lib/npm_cache/phonegap-template-blank/1.1.0/package","--id","com.phonegap.helloworld","--name","cordovaCopy"]
project-create-open-handlers.js:171 CREATE *START* AT: Mon, 15 Aug 2016 11:45:30 GMT
project-create-open-handlers.js:183 CREATE CLOSE *COMPLETE* AT Mon, 15 Aug 2016 11:45:32 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time to create project 1.141 seconds.
```
-------------------------------------------------------------------------------------------------

### Create project with template via NPM 

#### PhoneGap CLI (`phonegap create --template=phonegap-template-blank`...)
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/phonegap/bin/phonegap.js","create","/Users/hschinsk/phonegap-apps/pgTemplateTest","--template=phonegap-template-blank","--id","com.phonegap.helloworld","--name","pgTemplateTest"]
project-create-open-handlers.js:171 CREATE *START* AT: Mon, 15 Aug 2016 11:51:45 GMT
project-create-open-handlers.js:183 CREATE CLOSE *COMPLETE* AT Mon, 15 Aug 2016 11:52:30 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time to create project 44.992 seconds.
```
#### Cordova CLI (`cordova create --template=phonegap-template-blank`...)
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/cordova/bin/cordova","create","/Users/hschinsk/phonegap-apps/cordTemplateTest","--template=phonegap-template-blank","--id","com.blank.template","--name","cordTemplateTest"]
project-create-open-handlers.js:171CREATE *START* AT: Mon, 15 Aug 2016 11:49:46 GMT
project-create-open-handlers.js:183CREATE CLOSE *COMPLETE* AT Mon, 15 Aug 2016 11:50:25 GMT EXIT CODE 0
project-create-open-handlers.js:189Time to create project 39.596 seconds.
```
--------------------------------------------------------------------------------------------------

### Create project with template via GIT URL

#### PhoneGap CLI (`phonegap create --template=https://github.com/phonegap/phonegap-template-blank/`...)
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/phonegap/bin/phonegap.js","create","/Users/hschinsk/phonegap-apps/gitTestPG4","--template=https://github.com/phonegap/phonegap-template-blank/","--id","test.git.pg","--name","gitTestPG4"]
project-create-open-handlers.js:172 CREATE *START* AT: Mon, 15 Aug 2016 12:18:19 GMT
project-create-open-handlers.js:205 Retrieving https://github.com/phonegap/phonegap-template-blank/ using git...
project-create-open-handlers.js:205 Repository "https://github.com/phonegap/phonegap-template-blank/" checked out to git ref "master".
project-create-open-handlers.js:184 CREATE CLOSE *COMPLETE* AT Mon, 15 Aug 2016 12:18:56 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time to create project 36.884 seconds.
```

#### Cordova CLI (`cordova create --template=https://github.com/phonegap/phonegap-template-blank/`)
```
Args ["/Users/hschinsk/phonegap-app-desktop/www/node_modules/cordova/bin/cordova","create","/Users/hschinsk/phonegap-apps/testGitCordova","--template=https://github.com/phonegap/phonegap-template-blank/","--id","org.cordova.gittest","--name","testGitCordova"]
project-create-open-handlers.js:172 CREATE *START* AT: Mon, 15 Aug 2016 12:14:47 GMT
Retrieving https://github.com/phonegap/phonegap-template-blank/ using git...
project-create-open-handlers.js:205 Repository "https://github.com/phonegap/phonegap-template-blank/" checked out to git ref "master".
project-create-open-handlers.js:184 CREATE CLOSE *COMPLETE* AT Mon, 15 Aug 2016 12:14:51 GMT EXIT CODE 0
project-create-open-handlers.js:189 Time to create project 3.512 seconds.
```

**Comment by purplecabbage** [comment]
Is this pr ever to be merged? It is huge and conflicty.

**Comment by hermwong** [comment]
Not yet, planning to merge it today.

**Pull request merged**
