### PR TITLE
Added linux config information to the electron build options.

### PR DESCRIPTION
**Pull request by daniel-childs**
Small change that added linux64 support in the build options.  Tested this on my personal ubuntu-box and everything seems to be working so far.  I haven't tested this to see if it breaks Windows or OSX, and would love some feedback.

### CODE REVIEW

**Comment by elisaado** [comment]
Yaay! I'll test it too.
The build instructions for osx for fine on linux too, except for brew and stuff.

(I'll quickly forget to post the results here, if you want 'em, please tag me :p)

**Comment by daniel-childs** [comment]
Oh, yeah I guess I should probably add some build instructions, eh?

**Comment by surajpindoria** [comment]
The build instructions for OSX are out of date. They were mainly for older versions when we were building Windows from Mac. It should be ok to just install grunt and `npm install`.

**Comment by elisaado** [comment]
@daniel-childs nah, I think it's easy, still not done it tough.

**Comment by elisaado** [comment]
@surajpindoria, thanks!

**Comment by elisaado** [comment]
It works, even the animations! :p

I did this:
Cloned @daniel-childs his repository
Switched to the `linux-support` branch
`npm install` then `cd www`, and again `npm install`
Main repo dir: `cd ..`
Build it: `grunt`
Run it: (in the main repo dir) `./build/PhoneGap-linux-x64/PhoneGap`

And it should start.

**Comment by surajpindoria** [comment]
I am going to play around with this today and test it out. One thing for future reference @elisaado, you don't need to do an `npm install` inside `www/`. When you build using grunt we already have a task in place to do that for you.

**Comment by elisaado** [comment]
I see, thanks for the notice/tip :)

**Comment by enthusiasmus** [comment]
+1 Works for me on debian stretch 

```
git clone https://github.com/phonegap/phonegap-app-desktop
cd phonegap-app-desktop
npm install && cd www && npm install
node_modules/grunt/bin/grunt
npm install electron --save-dev --save-exact
node_modules/electron/cli.js www
```

`

**Comment by andytorres** [comment]
I'm using Mint 18.2 (Ubuntu based), and followed the instructions posted by @elisaado in [comment](https://github.com/phonegap/phonegap-app-desktop/pull/807#issuecomment-305727728), but when I run `npm install` into phonegap-desktop-app, I got this error. Please help me figure it out. Below is the full log. Thanks in advance.
```
andy@GDAI-Laptop ~/phonegap-app-desktop $ npm install
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
npm WARN deprecated buffer-browserify@0.0.5: Package not maintained. Recent browserify uses https://github.com/feross/buffer
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead
npm ERR! git clone --template=/home/andy/.npm/_git-remotes/_templates --mirror git://github.com/substack/sockjs-client.git /home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6: Cloning into bare repository '/home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6'...
npm ERR! git clone --template=/home/andy/.npm/_git-remotes/_templates --mirror git://github.com/substack/sockjs-client.git /home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/andy/.npm/_git-remotes/_templates --mirror git://github.com/substack/sockjs-client.git /home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6: github.com[0: 192.30.253.113]: errno=Connection timed out
npm ERR! git clone --template=/home/andy/.npm/_git-remotes/_templates --mirror git://github.com/substack/sockjs-client.git /home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6: github.com[1: 192.30.253.112]: errno=Connection timed out
npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/andy/.npm/_git-remotes/_templates --mirror git://github.com/substack/sockjs-client.git /home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6
npm ERR! Cloning into bare repository '/home/andy/.npm/_git-remotes/git-github-com-substack-sockjs-client-git-browserify-npm-21e968c6'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Connection timed out
npm ERR! github.com[1: 192.30.253.112]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andy/phonegap-app-desktop/npm-debug.log

```

**Comment by hermwong** [comment]
@andytorres looks like `npm install` is failing to install one of the required dev dependencies.

**Comment by hermwong** [comment]
I was able to get the app to run on Ubuntu - but there were 2 dependencies that I need to install to get the Desktop App to run on my Ubuntu VM.

I needed to install `wine-stable` and also `libgconf-2-4`.

I've done some basic testing - creating a project works and serving in a browser works.

I did notice a couple of rendering issues, I'm not sure if the issues are on the Electron side or if it's Ubuntu (or my Ubuntu VM).

Project Directory selector dialog in the create new project workflow - rendering issue
screen shot 2017-11-21 at 2 55 44 pm

PhoneGap - About dialog rendering issue
screen shot 2017-11-21 at 2 56 08 pm

The bottom status bar also seems is too high on Ubuntu. Will definitely need to go through and identify other visual quirks on Ubuntu.

**Comment by hermwong** [comment]
Successfully created a project and previewing it in the browser.

screen shot 2017-11-21 at 2 59 26 pm

**Comment by hermwong** [comment]
Updated to latest version of Electron (v1.7.9), it seemed to fix the render position of the status bar, however the file/directory selector and about dialog still have rendering issues.

screen shot 2017-11-21 at 3 59 09 pm

**Comment by andytorres** [comment]
Thanks for the feedback, @hermwong. One question, can I build the the phonegap app in ubuntu from the [phonegap-desktop-app](https://github.com/phonegap/phonegap-app-desktop) repo? I'm currently trying to build it from @daniel-childs  repository, linux-support branch.

**Comment by hermwong** [comment]
You can use @daniel-childs `linux-support` branch or you can use the `linux` branch on the PhoneGap Desktop repo (it contains @daniel-childs changes and some minor updates).

**Comment by daniel-childs** [comment]
@andytorres Yeah, you should probably stick with the default `linux` branch and not my fork. I haven't touched the code in a while.

Somewhat related, @hermwong, have you looked at using electron-builder for this project? They've got awesome support for cross platform installable electron packages. At some point I'll probably try wrapping this up into a snap package.

**Comment by hermwong** [comment]
@daniel-childs I haven't had a chance to look at `electron-builder` yet. My work priorities have shifted a bit, so I haven't been able to put as much time into the PhoneGap Desktop App.

**Comment by andytorres** [comment]
Thanks for the feebback @hermwong and @daniel-childs. I cloned the [phonegap-app-desktop](https://github.com/phonegap/phonegap-app-desktop), checked out in `linux` branch, but I still got the same dependencies timeout error. It has something to do with browserify and sockjs-client. I'll dig into that. Thanks!

**Comment by Kronos35** [comment]
Tried installing using this code posted by enthusiasmus

`
git clone https://github.com/phonegap/phonegap-app-desktop
cd phonegap-app-desktop
npm install && cd www && npm install
npm install electron --save-dev --save-exact
node_modules/electron/cli.js www
`
But when I run the last line this message appears:
`bash: node_modules/electron/cli.js: No such file or directory
`

**Comment by elisaado** [comment]
@Kronos35 Have you tried switching to the `linux` branch :D?

**Pull request closed without merging**
